services:
  app:
    container_name: gameroomexperienceserver
    build: .
    restart: always
    environment:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      PUPPETEER_EXECUTABLE_PATH: "/usr/bin/google-chrome-stable"
    volumes:
      - ./storage:/app/storage
    ports:
      - "${BACK_END_PORT}:3000"
    env_file:
      - .env
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db