services:
  app:
    container_name: gameroomexperienceserver
    build: .
    restart: always
    volumes:
      - .:/app
    environment:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      PUPPETEER_EXECUTABLE_PATH: "/usr/bin/google-chrome-stable"
    ports:
      - "3000:3000"
    env_file:
      - keys.env
    command: node index.js
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: